# Generated by Django 5.2.17 on 2026-09-10 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_telegramnotice_order_alter_lead_status_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость (KZT)'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='выполнен'),
        ),
        migrations.AddField(
            model_name='order',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='leads.lead', verbose_name='исходный лид'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='оплачен'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен мастер'), ('in_progress', 'В работе'), ('completed', 'Выполнен, ожидает оплаты'), ('paid', 'Оплачен')], db_index=True, default='new', max_length=20, verbose_name='этап'),
        ),
    ]
