# Generated by Django 5.2.17 on 2026-09-11 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='получено мастером (KZT)'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='мастер сообщил об оплате'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('card', 'Карта')], max_length=20, verbose_name='способ оплаты'),
        ),
    ]
