# Generated by Django 5.2.17 on 2026-09-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_received_amount_order_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='причина отмены'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата отмены'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначен мастер'), ('in_progress', 'В работе'), ('completed', 'Выполнен, ожидает оплаты'), ('paid', 'Оплачен'), ('cancelled', 'Отменён клиентом')], db_index=True, default='new', max_length=20, verbose_name='этап'),
        ),
    ]
