# Generated by Django 5.2.17 on 2026-09-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_cancellation_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='repeat_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repeat_repairs', to='orders.order', verbose_name='повторный ремонт заказа'),
        ),
    ]
