# Generated by Django 5.2.17 on 2026-09-13 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_repeat_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='расходы (KZT)'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_comment',
            field=models.TextField(blank=True, max_length=2000, verbose_name='что сделано'),
        ),
        migrations.AddField(
            model_name='order',
            name='worker_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='процент мастера при оплате'),
        ),
    ]
