# Generated by Django 5.2.17 on 2026-09-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_appliance_type_order_brand_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='завершён бесплатно'),
        ),
    ]
