# Generated by Django 5.2.17 on 2026-09-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='worker_percentage',
        ),
    ]
