# Generated by Django 5.2.17 on 2026-09-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_city'),
        ('orders', '0013_remove_order_worker_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.city', verbose_name='город'),
        ),
    ]
