# Generated by Django 5.2.17 on 2026-09-10 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='принимает новые лиды'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_active_leads',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='лимит активных лидов'),
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employees', to='services.service', verbose_name='умеет выполнять услуги'),
        ),
    ]
