# Generated by Django 5.2.17 on 2026-09-10 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_available_user_max_active_leads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Telegram ID (личный чат)'),
        ),
    ]
