# Generated by Django 5.2.17 on 2026-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Руководитель'), ('operator', 'Оператор'), ('worker', 'Мастер')], default='', max_length=12, verbose_name='роль'),
        ),
    ]
