# Generated by Django 5.2.17 on 2026-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_link_expires',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
