# Generated by Django 5.2.17 on 2026-09-13 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_telegram_link_expires_user_telegram_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='процент сотрудника'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Руководитель'), ('operator', 'Оператор'), ('curator', 'Куратор'), ('worker', 'Мастер')], default='', max_length=12, verbose_name='роль'),
        ),
    ]
