# Generated by Django 5.2.17 on 2026-09-13 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_percentage_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'curator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_workers', to=settings.AUTH_USER_MODEL, verbose_name='куратор мастера'),
        ),
    ]
