# Generated by Django 5.2.17 on 2026-09-13 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_workers', to=settings.AUTH_USER_MODEL, verbose_name='оператор мастера'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workers', to=settings.AUTH_USER_MODEL, verbose_name='руководитель мастера'),
        ),
    ]
