# Generated by Django 5.2.17 on 2026-09-18 07:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mobilesession'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='percentage',
        ),
        migrations.CreateModel(
            name='WorkerServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='процент мастера')),
                ('active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_rates', to='services.service')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ставка мастера по услуге',
                'verbose_name_plural': 'ставки мастеров по услугам',
                'constraints': [models.UniqueConstraint(fields=('worker', 'service'), name='unique_worker_service_rate')],
            },
        ),
    ]
