# Generated by Django 5.2.17 on 2026-09-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_percentage_workerservicerate'),
        ('customers', '0006_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_cities',
            field=models.ManyToManyField(blank=True, related_name='workers', to='customers.city', verbose_name='города работы'),
        ),
    ]
