# Generated by Django 5.2.17 on 2026-09-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='источник'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('won', 'Успешно завершён'), ('lost', 'Закрыт без сделки')], db_index=True, default='new', max_length=20, verbose_name='статус'),
        ),
    ]
