# Generated by Django 5.2.17 on 2026-09-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_source_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('assigned', 'Назначен'), ('won', 'Выполнен'), ('lost', 'Закрыт без сделки')], db_index=True, default='new', max_length=20, verbose_name='статус'),
        ),
    ]
