# Generated by Django 5.2.17 on 2026-09-10 17:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('cancelled', 'Отменено')], default='pending', max_length=12)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notices', to='leads.lead')),
            ],
        ),
    ]
