# Generated by Django 5.2.17 on 2026-09-10 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_telegrambotstate_telegramnotice'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notices', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('assigned', 'Назначен'), ('won', 'Выполнен'), ('converted', 'Создан заказ'), ('lost', 'Закрыт без сделки')], db_index=True, default='new', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='telegramnotice',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notices', to='leads.lead'),
        ),
        migrations.AddConstraint(
            model_name='telegramnotice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lead__isnull', False), ('order__isnull', True)), models.Q(('lead__isnull', True), ('order__isnull', False)), _connector='OR'), name='telegram_notice_one_target'),
        ),
    ]
