# Generated by Django 5.2.17 on 2026-09-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_client_normalized_phone'),
        ('leads', '0005_telegramnotice_order_alter_lead_status_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'permissions': [('view_analytics', 'Просмотр аналитики источников')], 'verbose_name': 'лид', 'verbose_name_plural': 'лиды'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='services.service', verbose_name='услуга'),
        ),
        migrations.CreateModel(
            name='IncomingCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True, verbose_name='ID звонка АТС')),
                ('phone', models.CharField(max_length=16, verbose_name='телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='customers.client')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_call', to='leads.lead')),
            ],
            options={
                'verbose_name': 'входящий звонок',
                'verbose_name_plural': 'входящие звонки',
            },
        ),
    ]
