# Generated by Django 5.2.17 on 2026-09-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_options_alter_lead_service_incomingcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotice',
            name='amount_prompt_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
