# Generated by Django 5.2.17 on 2026-09-12 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_telegramnotice_amount_prompt_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='закрыта без сделки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='причина отказа'),
        ),
    ]
