# Generated by Django 5.2.17 on 2026-09-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_lost_at_lead_lost_by_lead_lost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotice',
            name='reminder_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
