# Generated by Django 5.2.17 on 2026-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_telegramnotice_reminder_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotice',
            name='draft_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotice',
            name='draft_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotice',
            name='payment_step',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
