# Generated by Django 5.2.17 on 2026-09-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_telegramnotice_draft_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotice',
            name='draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
