# Generated by Django 5.2.17 on 2026-09-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_telegramnotice_draft_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='appliance_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='тип техники'),
        ),
        migrations.AddField(
            model_name='lead',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='бренд'),
        ),
        migrations.AddField(
            model_name='lead',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='комментарий'),
        ),
    ]
