# Generated by Django 5.2.17 on 2026-09-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_city'),
        ('leads', '0012_lead_appliance_type_lead_brand_lead_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='customers.city', verbose_name='город'),
        ),
    ]
