# Generated by Django 5.2.17 on 2026-09-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.CharField(blank=True, max_length=200, verbose_name='район'),
        ),
    ]
