# Generated by Django 5.2.17 on 2026-09-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16),
        ),
    ]
